workflows:
  android-workflow:
    name: Android Cordova workflow
    environment:
      groups:
        - keystore_credentials # <-- Includes KEYSTORE, KEYSTORE_PASSWORD, KEY_ALIAS_PASSWORD, KEY_ALIAS
        - google_play # <-- Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS - Store your google-services.json
        - other
      # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
      vars:
        GRADLE_PATH: /Users/builder/programs/gradle-5.6.4/bin
        ANDROID_SDK_ROOT: /Users/builder/programs/android-sdk-macosx
        RELEASE_DIR: /Users/builder/clone/platforms/android/app/build/outputs/apk/release
        KEYSTORE_PATH: '/tmp/keystore.keystore'
      xcode: 12.4
      node: 12
      npm: 6
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci
          cvm install 9.0.0
          cvm use 9.0.0                  
      - name: Add Android platform
        script: |
          set -x
          set -e
          echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/google-services.json
          cordova platform remove android --nosave
          cordova platform add android --confirm --no-interactive --noresources          
      - name: Build Android
        script: |
          set -x
          set -e
          echo $GRADLE_PATH
          export PATH=$GRADLE_PATH:$PATH
          echo $PATH
          export PATH=$GRADLE_PATH:$PATH && cordova build android --release --no-interactive --prod --device
          echo $CM_KEYSTORE | base64 --decode > $KEYSTORE_PATH
          UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
          jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore "${KEYSTORE_PATH}" -storepass "${CM_KEYSTORE_PASSWORD}" -keypass "${CM_KEY_PASSWORD}" "${UNSIGNED_APK_PATH}" "${CM_KEY_ALIAS}"
          mv $UNSIGNED_APK_PATH $(echo $UNSIGNED_APK_PATH | sed 's/-unsigned//')          
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/mapping.txt
